### PR TITLE
Tolerances are expected negative in processOutputOutOfRange function

### PR DESCRIPTION
**Pull request by aksoysamet**
In the process of output range checking, tolerances are expected negative. Tolerances of aux data v2.1 are also negative. Because of that signs of tolerances have been changed to negative.

### CODE REVIEW

**Comment by Florian1209** [comment]
Thank you very much  for your contribution.

I would prefer to change the logic of the function ( https://github.com/senbox-org/s2tbx/blob/a60105669de6438637ae4796e5d5e00e2f76f668/s2tbx-biophysical/src/main/java/org/esa/s2tbx/biophysical/BiophysicalAlgo.java#L182 )
instead of modify the data files because this files follow the original data edited by INRA.

I plan this change on this JIRA ticket https://senbox.atlassian.net/browse/SIITBX-444

**Comment by aksoysamet** [comment]
Thank you for your quick response. I guess it has to wait till to full INRA data.

**Comment by Florian1209** [comment]
I got the INRA data and I have to submit a merge request for the SNAP-444 these days (the code is available on snap-444 branch).

**Comment by aksoysamet** [comment]
Okay, I just saw the latest commits. I have also noticed that LAI_CW tolerances are negative in the INRA data.

https://github.com/senbox-org/s2tbx/blob/1f5cd91e8bd6e49c4f94951bc8bc8791cb4b54f9/s2tbx-biophysical/src/main/resources/auxdata/3_0/S2A/LAI_Cw/LAI_Cw_ExtremeCases#L1

https://github.com/senbox-org/s2tbx/blob/1f5cd91e8bd6e49c4f94951bc8bc8791cb4b54f9/s2tbx-biophysical/src/main/resources/auxdata/3_0/S2B/LAI_Cw/LAI_Cw_ExtremeCases#L1

I think, in order to resolve the sign issue, tolerances could be converted to absolute values.

**Comment by Florian1209** [comment]
The INRA data isn't correct in this case.
Yes, you are right with absolute value, it is more secure. I fix with the absolute value and update data also.
Thank you once again.

**Pull request closed without merging**
