### PR TITLE
S2tbx gdal geotiff gcp

### PR DESCRIPTION
**Pull request by oanahogoiu**
Enable COG from GDAL and corrections for GCP

### CODE REVIEW

**Comment by marpet** [comment]
Is there something special I should look at? Otherwise please just go on. It does affect only S2TBX. Nothing that I need to review.

**Comment by oanahogoiu** [comment]
Marco, we just wanted to make sure you agree about enabling GeoTIFF driver from GDAL. When opening in SNAP a tiff, 2 available readers will be found, named accordingly.

**Comment by marpet** [comment]
Actually I'm not much in favour of this. We just got rid of the choice shown to the user between GeoTiff and BigGeoTiff.
And I think it can change the behaviour of GPT processing if the reader is not explicitly declared. It can happen that the new gdal reader is used instead of the old reader. This probably changes the results.

**Comment by oanahogoiu** [comment]
Being able to read COG was the main reason of updating GDAL version. And COG has the same extension as GeoTIFF.
Regarding GPT, we have thought about that, but we haven't found tests using as input directly tiffs. The tests are using the metadata file of a specific product format.
Plus, the GDAL GeoTIFF seems a lot faster than the GeoTIFF base reader from SNAP.

**Comment by marpet** [comment]
Maybe we can talk about it during the TC today

**Comment by oanahogoiu** [comment]
The GeoTIFF driver from GDAL is disabled now, after our discussion. The rest of the changes concern only GDAL, can I proceed with the merge?

**Review by marpet — APPROVED** [review]

**Comment by marpet** [comment]
Yes, go ahead please

**Pull request merged**
